name: SYFT ACTION UPLOAD

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  SYFT-ACTION-SBOM-upload:

    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Docker
      uses:  docker/setup-buildx-action@v3
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: simple_go_api
    - name: Build image
      uses: docker/build-push-action@v6
      with:
        tags: simple_go_api:latest
        outputs: type=docker,dest=/tmp/simple_go_api.tar
        push: false
    - name: Load Image
      run: docker load --input /tmp/simple_go_api.tar
    - name: Generate SBOM
      uses: anchore/sbom-action@v0
      with:
        image: simple_go_api:latest
        dependency-snapshot: true
        upload-artifact: true
        
      


