name: SYFT SBOM upload

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  SYFT-SBOM-upload:

    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Docker
      uses:  docker/setup-buildx-action@v3
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE_NAME }}
    - name: Build service
      uses: docker/build-push-action@v6
      with:
        push: false

    - name: Generate SBOM
      # generation command documentation: https://github.com/microsoft/sbom-tool#sbom-generation
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /$RUNNER_TEMP
        chmod +x $RUNNER_TEMP/syft
        mkdir $RUNNER_TEMP/sbom
        $RUNNER_TEMP/syft ./${{ env.IMAGE_NAME }} -o spdx-json@2.2 > $RUNNER_TEMP/sbom/spdx.json
    - name: SBOM upload
      uses: advanced-security/spdx-dependency-submission-action@v0.0.1
      with:
        filePath: $RUNNER_TEMP/sbom/


