name: SYFT SBOM upload

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  SYFT-SBOM-upload:

    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Docker
      uses:  docker/setup-buildx-action@v3
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: simple_go_api
    - name: Build image
      uses: docker/build-push-action@v6
      with:
        tags: simple_go_api:latest
        outputs: type=docker,dest=/tmp/simple_go_api.tar
        push: false

    - name: Generate SBOM
      # generation command documentation: https://github.com/microsoft/sbom-tool#sbom-generation
      run: |
        docker load --input /tmp/simple_go_api.tar
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /$RUNNER_TEMP
        chmod +x $RUNNER_TEMP/syft
        $RUNNER_TEMP/syft simple_go_api:latest -o spdx-json@2.2 | jq . > /tmp/spdx.json
    # - name: Logging SBOM
    #   run: |
    #     echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!CATTING\n$(cat $RUNNER_TEMP/sbom/spdx.json)"
    - uses: actions/upload-artifact@v4
      with:
        name: sbom
        path: /tmp/spdx.json
    - name: SBOM upload
      uses: advanced-security/spdx-dependency-submission-action@v0.1.1
      with:
        filePath: /tmp/
        filePattern: spdx.json


